import FooterBar from "@/components/Layout/FooterBar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme, { globalStyles } from "@/styles/theme";
import Head from "next/head";
import HeaderBar from "@/components/Layout/HeaderBar";
import Popup from "@/components/Popup";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui"
        />
        <meta name="apple-mobile-web-app-title" content="BestForming" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </Head>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          {globalStyles}
          <body>
            <HeaderBar />
            {children}
            {/* <FooterBar /> */}
            <Popup />
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
